version: "3.8"
services:
  postgres:
    container_name: gofinance_postgres
    image: postgres:15.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gofinance
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gofinance"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - gofinance_network
    restart: always

  app:
    container_name: gofinance_app
    build:
      context: ./
    image: meziaris/gofinance
    ports:
      - 3333:3333
    volumes:
       - ./app.env:/app/app.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gofinance_network
    restart: always

  migrate:
    image: migrate/migrate
    profiles:
      - tools
    networks:
      - gofinance_network
    volumes:
      - ./migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@postgres:5432/gofinance?sslmode=disable"
      ]
    command: "up"
    depends_on:
      - postgres

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  postgres:

networks:
  gofinance_network:
    driver: bridge
